name: Build & Publish
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile, pruner/Dockerfile]
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.dockerfile }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Short SHA
        uses: benjlevesque/short-sha@v2.1
        id: short-sha
      - name: Set Repository Name to Lowercase
        uses: ASzc/change-string-case-action@v5
        id: repo-tolower
        with:
          string: ${{ github.repository }}
      - name: Extract image name
        id: image-name
        run: |
          IMAGE_NAME=$(basename $(dirname ${{ matrix.dockerfile }}))
          if [ "$IMAGE_NAME" = "." ]; then
            IMAGE_NAME=""
          else
            IMAGE_NAME="-$IMAGE_NAME"
          fi
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
      - name: Extract dir name
        id: dir-name
        run: |
          DIR_NAME=$(basename $(dirname ${{ matrix.dockerfile }}))
          echo "DIR_NAME=$DIR_NAME" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.dir-name.outputs.DIR_NAME }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/${{ steps.repo-tolower.outputs.lowercase }}${{ steps.image-name.outputs.IMAGE_NAME }}:${{ steps.short-sha.outputs.sha }}
            ghcr.io/${{ steps.repo-tolower.outputs.lowercase }}${{ steps.image-name.outputs.IMAGE_NAME }}:latest
